# Generated by Django 2.1.2 on 2018-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster', '0002_auto_20181024_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_json',
        ),
        migrations.AddField(
            model_name='city',
            name='city_lat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_long',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_vicinity',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
