# Generated by Django 2.1.2 on 2018-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster', '0003_auto_20181025_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_lat', models.CharField(max_length=50)),
                ('hospital_lon', models.CharField(max_length=50)),
                ('hospital_vicinity', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name', models.CharField(max_length=100)),
                ('police_lat', models.CharField(max_length=50)),
                ('police_lon', models.CharField(max_length=50)),
                ('police_vicinity', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_long',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_vicinity',
        ),
    ]
