# Generated by Django 2.1.2 on 2018-10-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster', '0004_auto_20181025_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityhospital',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Disaster.City'),
            preserve_default=False,
        ),
    ]
